#ifndef ERRORS_HPP__
#define ERRORS_HPP__

typedef enum
{
    ERR_OK = 0,
    ERR_WRONG_ARGS,
    ERR_WRONG_FILE,
    ERR_NULL_POINTER,
    ERR_NOT_INIT,
    ERR_WRONG_FILE_STRUCTURE,
    ERR_COULDNT_INIT_GRAPHICS,
    ERR_COULDNT_DRAW_POINT,
    ERR_COULDNT_DRAW_LINE,
    ERR_COULDNT_UPDATE_RENDER,
    ERR_COULDNT_SET_RENDER_COLOR,
    ERR_COULDNT_CLEAR_RENDER,
    ERR_MEM_ALLOC,
} errCode;

#endif // !ERRORS_HPP__
